.editorconfig, run-tests.sh
* Added invenio_db as known third party to editorconfig
Signed-off-by: Krzysztof Nowak <kn@linux.com>
=> testing: temporary solution to isort

invenio_admin/__init__.py, invenio_admin/ext.py, tests/demo/onetwo.py, tests/demo/three.py, tests/test_invenio_admin.py
* Adds categories and other customization kwargs to admin entry point.
=> setup: categories and custom kwargs in ep loading

INSTALL.rst, invenio_admin/__init__.py, invenio_admin/config.py, invenio_admin/ext.py, invenio_admin/permissions.py, invenio_admin/views.py, requirements-devel.txt, run-tests.sh, setup.py, tests/conftest.py, tests/test_invenio_admin.py
* NEW Adds access control to admin interface using Invenio-Access.
=> global: access control

.travis.yml, CHANGES.rst, INSTALL.rst, RELEASE-NOTES.rst, invenio_admin/__init__.py, invenio_admin/config.py, invenio_admin/ext.py, invenio_admin/permissions.py, invenio_admin/version.py, invenio_admin/views.py, requirements-devel.txt, run-tests.sh, setup.py, tests/conftest.py, tests/test_invenio_admin.py
=> release: v1.0.0a1

invenio_admin/version.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> version: post-release bump

invenio_admin/views.py, requirements-devel.txt, setup.py
=> global: flask security 1.7.5 fix

CHANGES.rst, RELEASE-NOTES.rst, invenio_admin/version.py
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> release: v1.0.0a2

invenio_admin/filters.py, invenio_admin/forms.py, tests/conftest.py, tests/test_filters.py, tests/test_forms.py
* Adds support for filters on UUID column types.
* Adds support for columns with variant data types.
=> filters: UUID and variant filter support

CHANGES.rst, RELEASE-NOTES.rst, invenio_admin/version.py
=> release: v1.0.0a3

.editorconfig, .travis.yml, run-tests.sh
Signed-off-by: Jiri Kuncar <jiri.kuncar@cern.ch>
=> travis: custom PyPy installation

.travis.yml, .tx/config, invenio_admin/translations/cs/LC_MESSAGES/messages.po, invenio_admin/translations/da/LC_MESSAGES/messages.po, invenio_admin/translations/de/LC_MESSAGES/messages.po, invenio_admin/translations/es/LC_MESSAGES/messages.po, invenio_admin/translations/fr/LC_MESSAGES/messages.po, invenio_admin/translations/it/LC_MESSAGES/messages.po
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
=> i18n: tx config and travis fix

AUTHORS.rst, docs/conf.py, invenio_admin/ext.py, invenio_admin/permissions.py
* Improves documentation. (addresses #22)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> docs: addition of param and result sections

docs/index.rst
Signed-off-by: Alizee Pace <alizee.pace@gmail.com>
=> docs: fix module name

examples/app-fixtures.sh, examples/app-setup.sh, examples/app-teardown.sh, examples/app.py, examples/requirements.txt, tests/test_examples_app.py
* Adds test_examples_app.py. (closes #29)
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> tests: addition of test_examples_app.py

.editorconfig, .gitignore, .travis.yml, CONTRIBUTING.rst, INSTALL.rst, README.rst, RELEASE-NOTES.rst, docs/Makefile, docs/api.rst, docs/conf.py, docs/configuration.rst, docs/make.bat, docs/usage.rst, examples/app.py, invenio_admin/config.py, invenio_admin/ext.py, run-tests.sh, setup.cfg, setup.py, tests/demo/__init__.py, tests/test_invenio_admin.py
=> [feature-beta] global: synchronization with cookiecutter template

invenio_admin/ext.py, invenio_admin/filters.py, invenio_admin/forms.py, invenio_admin/views.py
Signed-off-by: Alexander Ioannidis <a.ioannidis@cern.ch>
=> [feature-beta] docs: api docstring fixes

docs/index.rst, invenio_admin/__init__.py, invenio_admin/config.py, invenio_admin/ext.py, invenio_admin/views.py, tests/conftest.py, tests/demo/four.py, tests/test_invenio_admin.py
* Adds configuration for custom admin permission factory.
* Adds entry point interface for Flask-Admin BaseViews
=> global: permission factory and base views

invenio_admin/__init__.py
=> docs: minor docs fixes

invenio_admin/__init__.py, invenio_admin/views.py
=> global: proxy importable from root package

CHANGES.rst, RELEASE-NOTES.rst, invenio_admin/version.py
=> release: v1.0.0b1

CHANGES.rst, RELEASE-NOTES.rst, invenio_admin/version.py
Signed-off-by: Nikos Filippakis <nikolaos.filippakis@cern.ch>
=> release: v1.0.0b2

invenio_admin/views.py, tests/test_invenio_admin.py
- override Talisman configuration @before_request to set CSP to None
- remove CSP response header
- fixes #56
=> Remove CSP header for admin views which was broken Flask-Admin forms

CHANGES.rst, RELEASE-NOTES.rst, examples/app-setup.sh, invenio_admin/version.py, setup.py
Signed-off-by: Leonardo Rossi <leonardo.r@cern.ch>
=> release: v1.0.0b4

examples/app-fixtures.sh, examples/app.py, invenio_admin/permissions.py, tests/conftest.py, tests/test_invenio_admin.py
=> tests: update test_default_permission

docs/conf.py, setup.py, tests/test_examples_app.py
* Flask-Admin <=1.5.2 is vulnerable to an XSS attack.
=> installation: flask-admin v1.5.3

invenio_admin/ext.py
=> global: fix deprecation warning

.travis.yml, CHANGES.rst, invenio_admin/version.py, requirements-devel.txt, setup.py
* pinns Flask-Login, updates python dependencies
closes #85
=> global: replace flask dependency with invenio-base

.github/workflows/tests.yml, invenio_admin/ext.py, invenio_admin/permissions.py, setup.py, tests/test_invenio_admin.py
* Replaces `pkg_resources` with `importlib_metadata`.
=> ext: replace pkg_resources

setup.cfg
:heart: Thank you for your contribution!
Close https://github.com/inveniosoftware/invenio-accounts/issues/496
> Please describe briefly your pull request.
v3.2.0 makes a breaking change https://wtforms.readthedocs.io/en/3.2.x/changes/
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
* If you have added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Frontend**
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) …
=> setup: pin wtforms

CHANGES.rst, docs/conf.py, invenio_admin/__init__.py, setup.cfg, tests/test_invenio_admin.py
- **setup: pin wtforms**
- **📦 release: v1.4.1**
=> Backport wtforms pin to v1.4.x and release v1.4.1
